export const COLOR_TOKENS = {
  light: {
    surfacePage: "#f8fafc",
    surfacePageAlt: "#ffffff",
    surfaceMuted: "#f1f5f9",
    surfaceHover: "#e2e8f0",
    surfaceOverlay: "rgba(255, 255, 255, 0.8)",
    surfaceOverlaySoft: "rgba(248, 250, 252, 0.4)",
    textPrimary: "#0f172a",
    textHeading: "#0f172a",
    textSecondary: "#334155",
    textMuted: "#64748b",
    borderDefault: "rgba(15, 23, 42, 0.08)",
    borderSubtle: "rgba(15, 23, 42, 0.04)",
    borderInput: "#cbd5e1",
    brandPrimary: "#4f46e5",
    brandPrimaryStrong: "#3730a3",
    brandPrimaryHover: "#6366f1",
    brandSecondary: "#0f172a",
    brandAccent: "#d946ef",
    onPrimary: "#ffffff",
    onWarning: "#000000",
    focusOutline: "#1d4ed8",
    focusShadow: "rgba(191, 219, 254, 0.75)",
    skipFocus: "#facc15",
    success: "#22c55e",
    successSoft: "#f0fdf4",
    successBorder: "#86efac",
    successText: "#15803d",
    warning: "#f59e0b",
    warningSoft: "#fefce8",
    warningBorder: "#fde047",
    warningText: "#a16207",
    danger: "#ef4444",
    dangerSoft: "#fef2f2",
    dangerBorder: "#fca5a5",
    dangerText: "#dc2626",
    neutral: "#6b7280",
    neutralSoft: "#f3f4f6",
    neutralStrong: "#374151",
    footerAccent: "#74b9ff",
    shadowSubtle: "rgba(15, 23, 42, 0.08)",
    shadowMedium: "rgba(0, 0, 0, 0.15)",
    shadowBrand: "rgba(102, 126, 234, 0.3)",
    glowBrand: "rgba(59, 130, 246, 0.2)",
  },
  dark: {
    surfacePage: "#030712",
    surfacePageAlt: "#111827",
    surfaceMuted: "#111827",
    surfaceHover: "#1f2937",
    surfaceOverlay: "rgba(255, 255, 255, 0.1)",
    surfaceOverlaySoft: "rgba(255, 255, 255, 0.02)",
    textPrimary: "#f9fafb",
    textHeading: "#ffffff",
    textSecondary: "#cbd5e1",
    textMuted: "#9ca3af",
    borderDefault: "rgba(255, 255, 255, 0.08)",
    borderSubtle: "rgba(255, 255, 255, 0.04)",
    borderInput: "#475569",
    brandPrimary: "#6366f1",
    brandPrimaryStrong: "#818cf8",
    brandPrimaryHover: "#4f46e5",
    brandSecondary: "#0f172a",
    brandAccent: "#d946ef",
    onPrimary: "#ffffff",
    onWarning: "#000000",
    focusOutline: "#93c5fd",
    focusShadow: "rgba(30, 64, 175, 0.55)",
    skipFocus: "#facc15",
    success: "#22c55e",
    successSoft: "#052e16",
    successBorder: "#166534",
    successText: "#bbf7d0",
    warning: "#f59e0b",
    warningSoft: "#422006",
    warningBorder: "#92400e",
    warningText: "#fde68a",
    danger: "#ef4444",
    dangerSoft: "#450a0a",
    dangerBorder: "#991b1b",
    dangerText: "#fecaca",
    neutral: "#6b7280",
    neutralSoft: "#1f2937",
    neutralStrong: "#4b5563",
    footerAccent: "#74b9ff",
    shadowSubtle: "rgba(0, 0, 0, 0.35)",
    shadowMedium: "rgba(0, 0, 0, 0.4)",
    shadowBrand: "rgba(59, 130, 246, 0.3)",
    glowBrand: "rgba(99, 102, 241, 0.3)",
  },
};

const normalizeThemeTokens = (tokens) => ({
  surfacePage: tokens.surfacePage ?? tokens["--bg-color"],
  surfacePageAlt: tokens.surfacePageAlt ?? tokens["--card-bg-color"],
  surfaceMuted:
    tokens.surfaceMuted ??
    tokens["--bg-secondary"] ??
    tokens["--input-bg"] ??
    tokens["--card-bg-color"],
  surfaceHover: tokens.surfaceHover ?? tokens["--border-color"],
  textPrimary: tokens.textPrimary ?? tokens["--text-color"],
  textSecondary: tokens.textSecondary ?? tokens["--text-color-light"],
  textMuted: tokens.textMuted ?? tokens["--text-color-light"],
  borderDefault: tokens.borderDefault ?? tokens["--border-color"],
  borderInput: tokens.borderInput ?? tokens["--border-color"],
  brandPrimary: tokens.brandPrimary ?? tokens["--primary-color"],
  brandPrimaryStrong: tokens.brandPrimaryStrong ?? tokens["--primary-color"] ?? tokens.brandPrimary,
  brandPrimaryHover:
    tokens.brandPrimaryHover ?? tokens["--primary-hover"] ?? tokens["--primary-color"],
  brandSecondary: tokens.brandSecondary ?? tokens["--secondary-color"],
  brandAccent: tokens.brandAccent ?? tokens["--secondary-color"] ?? tokens.brandSecondary,
  glowBrand: tokens.glowBrand ?? tokens["--glow-color"],
  shadowSubtle: tokens.shadowSubtle ?? "rgba(0, 0, 0, 0.12)",
  dangerSoft: tokens.dangerSoft ?? COLOR_TOKENS.light.dangerSoft,
  dangerBorder: tokens.dangerBorder ?? COLOR_TOKENS.light.dangerBorder,
  dangerText: tokens.dangerText ?? COLOR_TOKENS.light.dangerText,
  successSoft: tokens.successSoft ?? COLOR_TOKENS.light.successSoft,
  successBorder: tokens.successBorder ?? COLOR_TOKENS.light.successBorder,
  successText: tokens.successText ?? COLOR_TOKENS.light.successText,
  warningSoft: tokens.warningSoft ?? COLOR_TOKENS.light.warningSoft,
  warningBorder: tokens.warningBorder ?? COLOR_TOKENS.light.warningBorder,
  warningText: tokens.warningText ?? COLOR_TOKENS.light.warningText,
});

export const createThemeVariables = (tokens) => {
  const theme = normalizeThemeTokens(tokens);

  return {
    ...tokens,
    "--bg-color": theme.surfacePage,
    "--bg-secondary": theme.surfaceMuted,
    "--bg-secondary-color": theme.surfaceMuted,
    "--bg-gradient": `linear-gradient(135deg, ${theme.surfacePage} 0%, ${theme.surfaceMuted} 100%)`,
    "--text-color": theme.textPrimary,
    "--text-color-light": theme.textSecondary,
    "--border-color": theme.borderDefault,
    "--card-bg-color": theme.surfacePageAlt,
    "--card-border": `1px solid ${theme.borderDefault}`,
    "--card-shadow": `0 4px 16px ${theme.shadowSubtle}`,
    "--card-shadow-color": theme.shadowSubtle,
    "--navbar-bg": tokens["--navbar-bg"] ?? theme.surfacePageAlt,
    "--sidebar-bg": tokens["--sidebar-bg"] ?? theme.surfacePageAlt,
    "--input-bg": tokens["--input-bg"] ?? theme.surfacePageAlt,
    "--input-text": tokens["--input-text"] ?? theme.textPrimary,
    "--input-border": theme.borderInput,
    "--input-placeholder": theme.textMuted,
    "--input-focus-border": theme.brandPrimaryStrong,
    "--input-focus-ring": theme.glowBrand,
    "--table-bg": tokens["--table-bg"] ?? theme.surfacePageAlt,
    "--modal-bg": tokens["--modal-bg"] ?? theme.surfacePageAlt,
    "--surface-muted": theme.surfaceMuted,
    "--surface-hover": theme.surfaceHover,
    "--primary-color": theme.brandPrimary,
    "--primary-hover": theme.brandPrimaryHover,
    "--secondary-color": theme.brandSecondary,
    "--color-primary-hover": theme.brandPrimaryHover,
    "--accent-gradient":
      tokens["--accent-gradient"] ??
      `linear-gradient(135deg, ${theme.brandPrimary} 0%, ${theme.brandAccent} 100%)`,
    "--glow-color": theme.glowBrand,
    "--danger-bg": theme.dangerSoft,
    "--danger-border": theme.dangerBorder,
    "--danger-text": theme.dangerText,
    "--success-bg": theme.successSoft,
    "--success-border": theme.successBorder,
    "--success-text": theme.successText,
    "--warning-bg": theme.warningSoft,
    "--warning-border": theme.warningBorder,
    "--warning-text": theme.warningText,
  };
};

export const DEFAULT_THEME_VARIABLES = {
  light: createThemeVariables(COLOR_TOKENS.light),
  dark: createThemeVariables(COLOR_TOKENS.dark),
};
